/**
 * A11yPanel - Interactive Visual UI Panel for Table Accessibility Editing
 */

function escapeHtml(s) {
  return String(s ?? "").replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
}

function renderA11yPanel(container, cell, table, onChange) {
  if (!container || !cell || !table) return;

  const cellId = cell.id || `c_${cell.row ?? 0}_${cell.col ?? 0}`;
  const isHeader = Boolean(cell.isHeader ?? cell.is_header ?? (cell.row === 0));

  const a11y = table.accessibility?.cells?.[cellId] || {
    role: isHeader ? "th" : "td",
    scope: isHeader ? (cell.colSpan > 1 ? "colgroup" : (cell.rowSpan > 1 ? "rowgroup" : "col")) : null,
    headers: [],
    autoGenerated: true,
  };

  const tableCells = Array.isArray(table.cells) ? table.cells : [];
  const headerCandidates = tableCells.filter(c => {
    const cId = c.id || `c_${c.row ?? 0}_${c.col ?? 0}`;
    const explicitHead = (c.isHeader ?? c.is_header);
    const cIsHead = Boolean((explicitHead !== undefined && explicitHead !== null) ? explicitHead : (c.row === 0 || (table.accessibility?.cells?.[cId]?.role === "th")));
    return cIsHead && cId !== cellId;
  });

  container.innerHTML = `
    <div class="a11y-panel">
      <div class="a11y-panel-header">
        <h4><i class="fa-solid fa-universal-access" style="color:#38bdf8"></i> Erişilebilirlik (Hücre: ${escapeHtml(cellId)})</h4>
        ${a11y.autoGenerated
          ? `<span class="a11y-badge a11y-badge-auto"><i class="fa-solid fa-robot"></i> Otomatik</span>`
          : `<span class="a11y-badge a11y-badge-manual"><i class="fa-solid fa-hand"></i> Elle Düzenlendi</span>`}
      </div>

      <div class="a11y-field-row">
        <div class="a11y-field-col">
          <label class="a11y-label">Hücre Rolü (Role)</label>
          <select data-field="role" class="a11y-select">
            <option value="td" ${a11y.role === "td" ? "selected" : ""}>Veri Hücresi (&lt;td&gt;)</option>
            <option value="th" ${a11y.role === "th" ? "selected" : ""}>Başlık Hücresi (&lt;th&gt;)</option>
          </select>
        </div>

        <div class="a11y-field-col">
          <label class="a11y-label">Kapsam (Scope)</label>
          <select data-field="scope" class="a11y-select" ${a11y.role === "td" ? "disabled" : ""}>
            <option value="">— (Yok)</option>
            <option value="col" ${a11y.scope === "col" ? "selected" : ""}>col (Sütun)</option>
            <option value="row" ${a11y.scope === "row" ? "selected" : ""}>row (Satır)</option>
            <option value="colgroup" ${a11y.scope === "colgroup" ? "selected" : ""}>colgroup (Sütun Grubu)</option>
            <option value="rowgroup" ${a11y.scope === "rowgroup" ? "selected" : ""}>rowgroup (Satır Grubu)</option>
          </select>
        </div>
      </div>

      ${headerCandidates.length > 0 ? `
        <label class="a11y-label" style="margin-top:8px;">İlişkili Başlıklar (&lt;th&gt; Headers)</label>
        <div class="a11y-headers-list">
          ${headerCandidates.map(h => {
            const hId = h.id || `c_${h.row ?? 0}_${h.col ?? 0}`;
            const isChecked = Array.isArray(a11y.headers) && a11y.headers.includes(hId);
            const previewText = (h.text || h.content || `Başlık (R${h.row}C${h.col})`).trim();
            return `
              <label class="a11y-chip" title="${escapeHtml(previewText)}">
                <input type="checkbox" value="${escapeHtml(hId)}" ${isChecked ? "checked" : ""}/>
                <span class="a11y-chip-text">${escapeHtml(previewText.slice(0, 26))}${previewText.length > 26 ? '...' : ''}</span>
              </label>
            `;
          }).join("")}
        </div>
      ` : ''}
    </div>
  `;

  const roleSelect = container.querySelector('[data-field="role"]');
  const scopeSelect = container.querySelector('[data-field="scope"]');

  if (roleSelect) {
    roleSelect.addEventListener("change", e => {
      const newRole = e.target.value;
      if (scopeSelect) {
        scopeSelect.disabled = newRole === "td";
        if (newRole === "td") scopeSelect.value = "";
      }
      updateA11y(table, cellId, { role: newRole, scope: newRole === "th" ? (scopeSelect ? scopeSelect.value || "col" : "col") : null }, onChange);
    });
  }

  if (scopeSelect) {
    scopeSelect.addEventListener("change", e => {
      updateA11y(table, cellId, { scope: e.target.value || null }, onChange);
    });
  }

  container.querySelectorAll('.a11y-headers-list input').forEach(cb => {
    cb.addEventListener("change", () => {
      const checked = [...container.querySelectorAll('.a11y-headers-list input:checked')].map(el => el.value);
      updateA11y(table, cellId, { headers: checked }, onChange);
    });
  });
}

function updateA11y(table, cellId, patch, onChange) {
  if (!table) return;
  if (!table.accessibility) table.accessibility = { caption: null, summary: null, cells: {} };
  if (!table.accessibility.cells) table.accessibility.cells = {};

  table.accessibility.cells[cellId] = {
    ...table.accessibility.cells[cellId],
    ...patch,
    autoGenerated: false
  };

  if (typeof onChange === 'function') {
    onChange(table);
  }
}

if (typeof window !== "undefined") {
  window.A11yPanel = { renderA11yPanel, updateA11y, escapeHtml };
  window.renderA11yPanel = renderA11yPanel;
  window.updateA11y = updateA11y;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { renderA11yPanel, updateA11y, escapeHtml };
}
